args = commandArgs(TRUE)
print(args)
library("knitr")
knit(args[1])
name = paste(unlist(strsplit(args[1],split=".",fixed=T))[[1]],".tex",sep="")
auxname = paste(unlist(strsplit(args[1],split=".",fixed=T))[[1]],".aux",sep="")
system2("pdflatex",args=name)
system2("bibtex",args=auxname)
system2("pdflatex",args=name)
system2("pdflatex",args=name)
